language: python
sudo: false
cache: pip
branches:
  only:
    - master

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-twlatest
    - python: pypy
      env: TOXENV=pypy-twlatest
    - python: 3.5
      env: TOXENV=py35-twlatest
    - python: 2.7
      env: TOXENV=py27-twlowest
    - python: pypy
      env: TOXENV=pypy-twlowest
    - python: 3.5
      env: TOXENV=py35-twlowest
    - python: 2.7
      env: TOXENV=py27-bleeding
    - python: pypy
      env: TOXENV=pypy-bleeding
    - python: 3.5
      env: TOXENV=py35-bleeding
    - python: 3.5
      env: TOXENV=flake8
  allow_failures:
    - env: TOXENV=py27-bleeding
    - env: TOXENV=pypy-bleeding
    - env: TOXENV=py35-bleeding
install:
  # Upgrade packaging tools separately, so that other installations are
  # performed with the upgraded tools.
  - pip install -U pip setuptools wheel
  - pip install tox codecov
  - |
    if [ "${TOXENV::5}" == "pypy-" ]; then
      git clone --depth 1 https://github.com/yyuu/pyenv.git ~/.pyenv
      PYENV_ROOT="$HOME/.pyenv"
      PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
      pyenv install pypy-5.6.0
      pyenv global pypy-5.6.0
    fi

script:
  - tox

after_success:
  # Codecov needs combined coverage, and having the raw report in the test
  # output can be useful.
  - tox -e coverage-report
  - codecov

notifications:
  email: false
